import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex:1,
        flexDirection:"column",
        flexWrap: 'nowrap',
        padding:5,
        alignItems: 'center',
        justifyContent: 'center',
        },
    page: {
        flex: 1,
        width: "100%",
        paddingHorizontal: 18,
        paddingVertical: 20,
        alignItems: "center",
        justifyContent: "center",
        gap: 14,
    },
    card: {
        width: "100%",
        maxWidth: 520,
        borderRadius: 16,
        padding: 16,
        backgroundColor: "white",
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.08)",
        shadowColor: "black",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 3,
        gap: 10,
    },
    badgeRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        justifyContent: "center",
    },
    badge: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: "rgba(0,0,0,0.06)",
    },
    badgeText: {
        fontSize: 12,
        fontWeight: "600",
        color: "rgba(0,0,0,0.72)",
        letterSpacing: 0.2,
        textAlign: "center",
    },
    subtitleCenter: {
        fontSize: 14,
        textAlign: "center",
        color: "rgba(0,0,0,0.65)",
        lineHeight: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "rgba(0,0,0,0.86)",
        textAlign: "center",
    },
    listItem: {
        fontSize: 13,
        color: "rgba(0,0,0,0.70)",
        lineHeight: 18,
        textAlign: "center",
    },
    accentCinema: { backgroundColor: "#0B1220" },
    accentLojas: { backgroundColor: "#102A18" },
    accentRestaurantes: { backgroundColor: "#2A0F12" },
    accentPromocoes: { backgroundColor: "#1A1330" },
    accentMapa: { backgroundColor: "#0B2430" },
    heroTitle: {
        fontSize: 28,
        fontWeight: "800",
        textAlign: "center",
        color: "white",
        letterSpacing: 0.3,
    },
    heroSubtitle: {
        fontSize: 14,
        textAlign: "center",
        color: "rgba(255,255,255,0.82)",
        lineHeight: 20,
        marginTop: 6,
    },
    heroBox: {
        width: "100%",
        maxWidth: 520,
        borderRadius: 18,
        padding: 18,
        gap: 6,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.10)",
    },
    container_left:{
        flex:0.1,
        flexDirection:"row",
        flexWrap: 'nowrap',
        padding:2,
        },
    container_row:{
        flex:1,
        flexDirection:"row",
        flexWrap: 'nowrap',
        padding:5,
        alignItems: 'center',
        justifyContent: 'space-around',
    },
    text:{
        fontSize :12,
        textAlign: 'center',
        fontFamily: 'sans-serif-medium',
        },
    image:{
        borderWidth: 1,
        borderColor: 'black',
        height: 100,
        width: 200,
        },
        input:{
    borderRadius:6,
        },
    dark: {
        backgroundColor: '#ffebcd',
        color : 'black',
        },
    light:{
        backgroundColor: 'black',
        color : '#ffebcd',
        },
    btn:{
        borderRadius:8,
        elevation: 5,
        fontWeight : 'bold',
        backgroundColor: 'green',
        },
    link:{
        color:'blue',
        fontStyle: 'italic',
        textDecorationLine: 'underline',
    },
    header: {
        backgroundColor: 'smoke',
        padding: 30,
        alignItems: 'center',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: 'white',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 16,
        color: 'white',
        opacity: 0.9,
    },
    menuContainer: {
    backgroundColor: 'white',
    },
    menuButton: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 20,
        marginBottom: 4,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: 'black',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    menuIcon: {
        fontSize: 32,
        marginRight: 15,
    },
    menuText: {
        fontSize: 18,
        fontWeight: '600',
        color: 'black',
    },
    scrollContainer: {
        flex: 1,
        backgroundColor: 'white',
    }
})