import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#121212",
        paddingHorizontal: 16,
        paddingVertical: 20,
        alignItems: "center",
    },
    title: {
        color: "#ffffff",
        fontSize: 24,
        fontWeight: "700",
        marginBottom: 10,
        textAlign: "center",
    },
    infoBox: {
        width: "100%",
        maxWidth: 480,
        backgroundColor: "#1db954",
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginBottom: 12,
        alignItems: "center",
    },
    infoTitle: {
        color: "#121212",
        fontSize: 15,
        fontWeight: "700",
        textAlign: "center",
    },
    infoText: {
        color: "#121212",
        fontSize: 13,
        marginTop: 2,
        textAlign: "center",
    },
    lista: {
        width: "100%",
        maxWidth: 520,
    },
    listaContent: {
        alignItems: "center",
    },
    trackRow: {
        backgroundColor: "#1f1f1f",
        borderRadius: 10,
        padding: 10,
        marginBottom: 10,
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
        maxWidth: 480,
        height: 80,
    },
    cover: {
        width: 56,
        height: 56,
        borderRadius: 6,
    },
    trackInfo: {
        marginLeft: 12,
        width: 300,
        alignItems: "center",
        justifyContent: "center",
    },
    trackName: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
        width: "100%",
    },
    trackMeta: {
        color: "#b3b3b3",
        fontSize: 13,
        marginTop: 2,
        textAlign: "center",
        width: "100%",
    },
    scroll: {
        flex: 1,
        backgroundColor: "#f3f4f6",
    },
    menu: {
        backgroundColor: "#f3f4f6",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 16,
        paddingVertical: 20,
    },
    menuBtn: {
        width: "100%",
        maxWidth: 420,
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 20,
        marginBottom: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "black",
        shadowColor: "black",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 3,
    },
    menuBtnHover: {
        backgroundColor: "#e9e9e9",
        transform: [{ scale: 1.01 }],
    },
    menuLabel: {
        fontSize: 18,
        marginRight: 10,
        color: "black",
    },
    menuTxt: {
        fontSize: 18,
        fontWeight: "600",
        color: "black",
        textAlign: "center",
    }
});
